/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.ni.views;

import java.io.IOException;
import ni.edu.ni.Frame.Controllers.PnlVehicleShowController;
import ni.edu.ni.Frame.panels.PnlVehicleShowInfo;

/**
 *
 * @author Pablo
 */
public class IFSearch extends javax.swing.JInternalFrame {
    // agregar showall
    PnlVehicleShowInfo pnlShowInfo;
    PnlVehicleShowController pnlShowInfoController;
    // agregar showall control;
    /**
     * Creates new form IFSearch
     */
    public IFSearch() throws IOException {
        initComponents();
        init();
    }
    private void init() throws IOException
    {
        PrinPnl.removeAll();
        // la cosa del if de que si es vacio y ese mate ya tu sabe
        if (pnlShowInfo == null)
        {
            pnlShowInfo = new PnlVehicleShowInfo();
            pnlShowInfoController = new PnlVehicleShowController(pnlShowInfo);
            validate();
            repaint();
        }
        // al final pones validate();
        // y el repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrinPnl = new javax.swing.JPanel();

        PrinPnl.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PrinPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrinPnl;
    // End of variables declaration//GEN-END:variables
}
