/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.ni.Frame;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import ni.edu.ni.Frame.Controllers.PnlVehicleShowController;
import ni.edu.ni.Frame.panels.PnlVehicleShowInfo;

/**
 *
 * @author JADPA18
 */
public class JIntFrame extends javax.swing.JInternalFrame {
private PnlVehicleShowInfo pVShowInfo;
private PnlVehicleShowController pnlVehicleShowController;
    /**
     * Creates new form JInternalFrame
     */
    public JIntFrame() {
        initComponents();
        holis();
    }
    
    public void holis(){
    jPanelViews.removeAll();
    if(pVShowInfo==null){
        pVShowInfo= new PnlVehicleShowInfo();
        try {
            pnlVehicleShowController= new PnlVehicleShowController(pVShowInfo);
        } catch (IOException ex) {
            Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       } 
   
    jPanelViews.add(pVShowInfo, BorderLayout.CENTER);
    validate();
    repaint();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViews = new javax.swing.JPanel();

        jPanelViews.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanelViews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanelViews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelViews;
    // End of variables declaration//GEN-END:variables
}
