/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.ni.Frame;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import ni.edu.ni.Frame.Controllers.PnlVehicleShowController;
import ni.edu.ni.Frame.Controllers.dialogVehicleController;
import ni.edu.ni.Frame.dao.daoImpl.JsonVehicleImpl;
import ni.edu.ni.Frame.panels.DCreateV;
import ni.edu.ni.Frame.panels.PnlVehicleShowInfo;

import ni.edu.ni.Frame.dao.daoImpl.RandomTemplate;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ni.edu.ni.pojo.Vehicle;

/**
 *
 * @author JADPA18
 */
public class JIntFrame extends javax.swing.JInternalFrame {
    private PnlVehicleShowInfo pVShowInfo;
    private PnlVehicleShowController pnlVehicleShowController;
    DefaultTableModel tm;
    private DCreateV dCreate;
    private dialogVehicleController DVehicle_Controller;
    private JsonVehicleImpl jvdao;
    /**
     * Creates new form JInternalFrame
     */
    public JIntFrame() {
        initComponents();
        holis();
    }
    
    public void holis()
    {
        jPanelViews.removeAll();
        if(pVShowInfo == null)
        {
            pVShowInfo = new PnlVehicleShowInfo();
            try {
            pnlVehicleShowController= new PnlVehicleShowController(pVShowInfo);
            } catch (IOException ex) {
            Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
   
    jPanelViews.add(pVShowInfo, BorderLayout.CENTER);
    validate();
    repaint();
    
}

    public JPanel getjPanelViews() {
        return jPanelViews;
    }

    public void setjPanelViews(JPanel jPanelViews) {
        this.jPanelViews = jPanelViews;
    }
    
    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public DefaultTableModel getTm() {
        return tm;
    }

    public void setTm(DefaultTableModel tm) {
        this.tm = tm;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViews = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(225, 150));
        setPreferredSize(new java.awt.Dimension(159, 56));

        jPanelViews.setMinimumSize(new java.awt.Dimension(225, 150));
        jPanelViews.setLayout(new java.awt.BorderLayout());

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelViews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if (dCreate == null)
        {
            dCreate = new DCreateV(null, true);
            
            try {
                DVehicle_Controller = new dialogVehicleController(dCreate);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dCreate.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        Vehicle v = new Vehicle();
        int id;
        id = (int) tm.getValueAt(pVShowInfo.getTableInfo().getSelectedRow(), 0) ;
        //id = (int) pVShowInfo.getTableInfo().getSelectedRow();
        
        System.out.println(id);
        
        try {
            v = jvdao.findById(id);
        } catch (IOException ex) {
            Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //int datos[]= new int [pVShowInfo.getTableInfo().getRowCount()];
        tm= (DefaultTableModel) pVShowInfo.getTableInfo().getModel();
//        try {
//            jvdao= new JsonVehicleImpl();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        if (v != null)
        {
            try {
                jvdao.delete(v);
            } catch (IOException ex) {
                Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            tm.removeRow(pVShowInfo.getTableInfo().getSelectedRow());
            JOptionPane.showMessageDialog(null, "Eliminado exitosamente");
            return;
        }
        //int dato=(int) pVShowInfo.getTableInfo().getSelectedRow();
        //   jvdao.delete(jvdao.findById(dato));
        //datos=pVShowInfo.getTableInfo().getSelectedRows();
//        for (int dato : datos) {
//            try {
//                //System.out.println(dato);
//                jvdao.delete(jvdao.findById(dato));
//            } catch (IOException ex) {
//                Logger.getLogger(JIntFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//        }
        //int dato=(int) (tm.getValueAt(pVShowInfo.getTableInfo().getSelectedRow(),0));
        //int dato = pVShowInfo.getTableInfo().getSelectedRow();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanelViews;
    // End of variables declaration//GEN-END:variables
}
