/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.ni.Frame;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import ni.edu.ni.Frame.Controllers.PnlVehicleController;
import ni.edu.ni.Frame.Controllers.dialogVehicleController;
import ni.edu.ni.Frame.panels.PnlVehicle;
import ni.edu.ni.Frame.panels.PnlVehicleShowInfo;
import ni.edu.ni.views.DCreate;
import ni.edu.ni.Frame.panels.DCreateV;

/**
 *
 * @author JADPA18
 */
public class JVehicleApp extends javax.swing.JFrame {
    //dialogVehicle vehicleD;
    private PnlVehicle pnlVehicle;
    private PnlVehicleController pnlVehicleController;
    private dialogVehicleController DVehicle_Controller;
    private JIntFrame jIntFrame;
    private PnlVehicleShowInfo pnlVShowInfo;
    private DCreate DialogCreate;
    
    private DCreateV dCreate;

    /**
     * Creates new form j
     */
    public JVehicleApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mtNew = new javax.swing.JMenuItem();
        mtView = new javax.swing.JMenuItem();
        mtExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(deskPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Options");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mtNew.setText("New");
        mtNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtNewActionPerformed(evt);
            }
        });
        jMenu1.add(mtNew);

        mtView.setText("View");
        mtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtViewActionPerformed(evt);
            }
        });
        jMenu1.add(mtView);

        mtExit.setText("Exit");
        mtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtExitActionPerformed(evt);
            }
        });
        jMenu1.add(mtExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mtNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtNewActionPerformed
       // aqui implementamos, de esta manera deberia de ser maso en el views, ok?
        if (dCreate == null)
        {
            dCreate = new DCreateV(this, true);

            try {
                DVehicle_Controller = new dialogVehicleController(dCreate);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JVehicleApp.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        dCreate.setVisible(true);
       
//        if (DialogCreate == null)
//        {
//            DialogCreate = new DCreate(this, true);
//        }
    }//GEN-LAST:event_mtNewActionPerformed

    private void mtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtViewActionPerformed
        // TODO add your handling code here:
        jIntFrame= new JIntFrame();
       // jIntFrame.setSize( 1365,680 );
        //jIntFrame.setResizable(true);
        jIntFrame.setMaximizable(true);
        jIntFrame.setClosable(true);
        deskPane.add(jIntFrame);
        jIntFrame.setVisible(true);

        
    }//GEN-LAST:event_mtViewActionPerformed

    private void mtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mtExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVehicleApp().setVisible(true);
            }
        });
    }
    
    private void addComponent(JDesktopPane component) {
        deskPane.removeAll();        
        deskPane.add(component, BorderLayout.CENTER);
        validate();
        repaint();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mtExit;
    private javax.swing.JMenuItem mtNew;
    private javax.swing.JMenuItem mtView;
    // End of variables declaration//GEN-END:variables
}
